@host = https://localhost:7120
@hostId = 19483
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTcyMTNiYi1iOTU5LTRiNDAtYjAxOS0wZWRmYTcyNmM5ZTgiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJNYXJ0aW4iLCJqdGkiOiI0NmE3YjA2My05YmE0LTQ4YjQtOTg2My04OTZhMTM5M2FlZDQiLCJleHAiOjE2Njk3NTE0MzgsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.BHxx690T7pX_P8enyi7tFFTFf0GqJqiqdH4hclVsFvs

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Pupper",
    "description" : "Pupper menu",
    "sections" : [
        {
            "name" : "any good section name",
            "description" : "Beginners",
            "items": [
                {
                    "name" : "Nuggets",
                    "description" : "Deep Nuggets"
                }
            ]
        }
    ]
}