@host = https://localhost:7120

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYTliMDdlYi1jNjRkLTRjYmUtODI3OC01MWU5NTNlZjEzM2IiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJNYXJ0aW4iLCJqdGkiOiI2M2E5MDkwOC1hZTgxLTRhYWEtYTEwZi00YWY2NWMzNGJmN2EiLCJleHAiOjE2NjkzODI3NzMsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.aGl1YntlwXKV3ZDKC0P2SvlEU-vJHONzywvjZKvduYk