@host = https://localhost:7120

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNDMxN2JlZS1jNDYzLTQ5N2UtOGE4OS05ZjEyYzE5NGViYTgiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJNYXJ0aW4iLCJqdGkiOiJiMDExZjk3MS0xZTU2LTQ3YmUtOTE1OC0yNzBjNDFhNjkwZjgiLCJleHAiOjE2Njk2MzUwNTgsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.ehk__vLJ6Mjm3tcnCY3SI9xMaXs4gqrcoRwoxnpx5Ro